# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kservice': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/kactivities': '@stable'
    'frameworks/kdeclarative': '@stable'
    'frameworks/ksu': '@stable'
