#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2023 Harald Sitter <sitter@kde.org>

export QT_LOGGING_RULES="*=false"
exec kcmshell5 kcm_about-distro --args dump --platform offscreen
